# Generated by Django 2.1.5 on 2019-01-27 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketballEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('first_player', models.CharField(max_length=30)),
                ('second_player', models.CharField(max_length=30, null=True)),
                ('type', models.CharField(choices=[('tp', 'triple_point'), ('dp', 'double-point'), ('p', 'penalty'), ('pm', 'penalty-miss'), ('s', 'substitution')], max_length=2)),
            ],
            options={
                'ordering': ['time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasketballPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='player_images/')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('nationality', models.CharField(max_length=30)),
                ('position', models.CharField(choices=[('pg', 'point-guard'), ('sg', 'shooting-guard'), ('c', 'center'), ('pf', 'power-forward'), ('sf', 'small-forward')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasketballPlayerStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.IntegerField()),
                ('triple_points', models.IntegerField()),
                ('double_points', models.IntegerField()),
                ('rebound', models.IntegerField()),
                ('max_score_in_one_game', models.IntegerField()),
                ('best', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BasketballStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.IntegerField()),
                ('triple_points', models.IntegerField()),
                ('double_points', models.IntegerField()),
                ('fouls', models.IntegerField()),
                ('penalty_fouls', models.IntegerField()),
                ('rebounds', models.IntegerField()),
                ('when', models.CharField(choices=[('fi', 'first'), ('se', 'second'), ('th', 'third'), ('fo', 'fourth')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FollowedTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='FootballEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField()),
                ('first_player', models.CharField(max_length=30)),
                ('second_player', models.CharField(max_length=30, null=True)),
                ('type', models.CharField(choices=[('rc', 'red-card'), ('yc', 'yellow-card'), ('pm', 'penalty-miss'), ('g', 'goal'), ('gp', 'goal(p)'), ('s', 'substitution')], max_length=2)),
                ('in_extra', models.BooleanField(verbose_name='happened in extra time')),
            ],
            options={
                'ordering': ['time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FootballPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='player_images/')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('nationality', models.CharField(max_length=30)),
                ('position', models.CharField(choices=[('gk', 'goal-keeper'), ('dl', 'defender-left'), ('dc', 'defender-center'), ('dr', 'defender-right'), ('ml', 'midfielder-left'), ('mc', 'midfielder-center'), ('mr', 'midfielder-right'), ('fl', 'forward-left'), ('fc', 'forward-center'), ('fr', 'forward-right')], max_length=2)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FootballPlayerStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('appearance', models.IntegerField()),
                ('red_cards', models.IntegerField()),
                ('yellow_cards', models.IntegerField()),
                ('best', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FootballStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corners', models.IntegerField()),
                ('fouls', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('possession', models.FloatField()),
                ('shots', models.IntegerField()),
                ('shots_on_target', models.IntegerField()),
                ('passes', models.IntegerField()),
                ('pass_accuracy', models.FloatField()),
                ('yellow_cards', models.IntegerField()),
                ('red_cards', models.IntegerField()),
                ('offsides', models.IntegerField()),
                ('when', models.CharField(choices=[('f', 'first-half'), ('s', 'second-half'), ('t', 'total')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture_link', models.URLField()),
                ('name', models.CharField(max_length=30)),
                ('season_pre', models.IntegerField()),
                ('season_post', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('stadium', models.CharField(max_length=30)),
                ('week', models.IntegerField()),
                ('home_score', models.IntegerField(null=True)),
                ('away_score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchSummarySnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('time', models.IntegerField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheesy.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('p', 'photo'), ('v', 'video')], max_length=1)),
                ('title', models.CharField(max_length=50)),
                ('media_link', models.URLField()),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheesy.Match')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('b', 'basketball'), ('f', 'football')], max_length=1)),
                ('publish_date', models.DateTimeField()),
                ('text', models.TextField()),
                ('summary', models.TextField()),
                ('picture_link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('avatar', models.ImageField(upload_to='user_images/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheesy.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheesy.News')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='staff_images/')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheesy.News')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='team_images/')),
                ('name', models.CharField(max_length=30)),
                ('type', models.CharField(choices=[('f', 'football'), ('b', 'basketball')], default='football', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='TeamStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField()),
                ('matches', models.IntegerField()),
                ('won', models.IntegerField()),
                ('drawn', models.IntegerField()),
                ('lost', models.IntegerField()),
                ('goals_for', models.IntegerField()),
                ('goals_against', models.IntegerField()),
                ('goals_difference', models.IntegerField()),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheesy.League')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheesy.Team')),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheesy.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='away',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away', to='cheesy.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='cheesy.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheesy.League'),
        ),
        migrations.AddField(
            model_name='footballstat',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheesy.Match'),
        ),
        migrations.AddField(
            model_name='footballplayerstat',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheesy.League'),
        ),
        migrations.AddField(
            model_name='footballplayerstat',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheesy.FootballPlayer'),
        ),
        migrations.AddField(
            model_name='footballplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheesy.Team'),
        ),
        migrations.AddField(
            model_name='footballevent',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheesy.Match'),
        ),
        migrations.AddField(
            model_name='followedteam',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheesy.Team'),
        ),
        migrations.AddField(
            model_name='followedteam',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheesy.News'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='basketballstat',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheesy.Match'),
        ),
        migrations.AddField(
            model_name='basketballplayerstat',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheesy.League'),
        ),
        migrations.AddField(
            model_name='basketballplayerstat',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheesy.BasketballPlayer'),
        ),
        migrations.AddField(
            model_name='basketballplayer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheesy.Team'),
        ),
        migrations.AddField(
            model_name='basketballevent',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheesy.Match'),
        ),
    ]
