# Generated by Django 2.1.5 on 2019-01-31 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheesy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnAuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=40)),
                ('email', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=30)),
            ],
        ),
    ]
