# Generated by Django 2.1.5 on 2019-02-02 21:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheesy', '0002_unauthuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basketballplayerstat',
            old_name='rebound',
            new_name='rebounds',
        ),
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='league',
            name='weeks',
            field=models.IntegerField(default=32),
        ),
        migrations.AddField(
            model_name='news',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='related_news',
            field=models.ManyToManyField(blank=True, related_name='_news_related_news_+', to='cheesy.News'),
        ),
        migrations.AddField(
            model_name='news',
            name='seen',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='basketball_players',
            field=models.ManyToManyField(to='cheesy.BasketballPlayer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='football_players',
            field=models.ManyToManyField(to='cheesy.FootballPlayer'),
        ),
        migrations.AddField(
            model_name='profile',
            name='teams',
            field=models.ManyToManyField(to='cheesy.Team'),
        ),
        migrations.AddField(
            model_name='reply',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reply',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='footballplayer',
            name='position',
            field=models.CharField(choices=[('gk', 'دروازبان'), ('dl', 'مدافع-چپ'), ('dc', 'مدافع-وسط'), ('dr', 'مدافع-راست'), ('ml', 'هافبک-چپ'), ('mc', 'هافبک-وسط'), ('mr', 'هافبک-راست'), ('fl', 'مهاجم-چپ'), ('fc', 'مهاجم-وسط'), ('fr', 'مهاجم-راست')], max_length=2),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
