# Generated by Django 2.1.5 on 2019-02-03 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cheesy', '0003_auto_20190202_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchBasketballPlayerStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scores', models.IntegerField()),
                ('triple_points', models.IntegerField()),
                ('double_points', models.IntegerField()),
                ('rebounds', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MatchFootballPlayerStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('fouls', models.IntegerField()),
                ('passes', models.IntegerField()),
                ('sub', models.BooleanField()),
                ('sub_in', models.BooleanField(default=False)),
                ('sub_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='basketballevent',
            name='side',
            field=models.CharField(choices=[('h', 'home'), ('a', 'away')], default='h', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='footballevent',
            name='side',
            field=models.CharField(choices=[('h', 'home'), ('a', 'away')], default='h', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='type',
            field=models.CharField(choices=[('f', 'football'), ('b', 'basketball')], default='football', max_length=1),
        ),
        migrations.AlterField(
            model_name='basketballstat',
            name='double_points',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='basketballstat',
            name='fouls',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='basketballstat',
            name='penalty_fouls',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='basketballstat',
            name='rebounds',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='basketballstat',
            name='scores',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='basketballstat',
            name='triple_points',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='footballstat',
            name='corners',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='footballstat',
            name='fouls',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='footballstat',
            name='goals',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='footballstat',
            name='offsides',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='footballstat',
            name='pass_accuracy',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='footballstat',
            name='passes',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='footballstat',
            name='possession',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='footballstat',
            name='red_cards',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='footballstat',
            name='shots',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='footballstat',
            name='shots_on_target',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='footballstat',
            name='yellow_cards',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='matchfootballplayerstat',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheesy.Match'),
        ),
        migrations.AddField(
            model_name='matchfootballplayerstat',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheesy.FootballPlayer'),
        ),
        migrations.AddField(
            model_name='matchbasketballplayerstat',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheesy.Match'),
        ),
        migrations.AddField(
            model_name='matchbasketballplayerstat',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cheesy.BasketballPlayer'),
        ),
    ]
