# Generated by Django 2.1.5 on 2019-02-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheesy', '0004_auto_20190203_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='media_link',
            field=models.CharField(max_length=100000),
        ),
    ]
